config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "new", to: "games#new"
  get "score", to: "games#score"
  post "score", to: "games#score"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'open-uri'
require 'json'

class GamesController < ApplicationController
    def new
        alphabet = ('A'..'Z').to_a
        @letters = Array.new(10) { alphabet.sample }
    end

    def score
        word = params[:word]
        letters = params[:letters].split(' ')

        if word.upcase.chars.all? { |char| letters.include?(char) }
            url = "https://wagon-dictionary.herokuapp.com/#{word}"
            response = URI.open(url).read
            result = JSON.parse(response)
            if result['found']
                @score = "Congratulations! #{word} is a valid English word!"
            else
                @score = "Sorry but #{word} is not a valid English word."
            end
        else
            @score = "Sorry but #{word} can't be built out of  #{letters.join(', ')}."
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<div class="container my-5">
      <h1 class="text-center mb-5">New game</h1>

      <div class="row justify-content-center mb-5">
        <% @letters.each do |letter| %>
          <div class="col-auto">
            <div class="bg-primary text-center text-white p-3 rounded">
              <%= letter %>
            </div>
          </div>
        <% end %>
      </div>

      <div class="row justify-content-center">
  <div class="col-md-6">
    <div class="card p-4">
      <%= form_tag(score_path, method: "get", data: { turbo: false }) do %>
        <div class="form-group mb-3">
          <%= text_field_tag :word, nil, class: "form-control", placeholder: "Enter a word" %>
        </div>
        <div class="d-grid gap-2">
          <%= submit_tag "Play", class: "btn btn-primary btn-block" %>
        </div>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <%= hidden_field_tag :letters, @letters %>
      <% end %>
    </div>
  </div>
</div>




app/views/games/score.html.erb
<div class="container-fluid d-flex justify-content-center align-items-center" style="height: 100vh;">
  <div class="card p-5">
    <h1 class="text-center mb-4">Result</h1>
    <p class="text-center display-4 mb-4"><%= @score %></p>
    <div class="d-flex justify-content-center">
      <%= link_to "Play again", new_path, class: "btn btn-success btn-lg" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>